apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mbsp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-mbsp@sha256:93c68257bc5f81fef979e81137883c40669ef3e2e3709cdec131a5d588bbdc56
        name: my-nodejs
        resources: {}
status: {}
